SAMPLE_DIR: "/var/lib/minknow/data"

OUT_DIR: "/home/nanopore/sequencing-data"

# to see available guppy models: `guppy_basecaller --print_workflows`
# SUP MODEL
GUPPY_MODEL: "dna_r10.4.1_e8.2_260bps_sup.cfg"
